---
# Source: kiali/charts/kiali-operator/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kiali-kiali-operator
  namespace: "kiali"
  labels:
    helm.sh/chart: kiali-operator-2.6.0
    app: kiali-operator
    app.kubernetes.io/name: kiali-operator
    app.kubernetes.io/instance: kiali
    version: "v2.6.0"
    app.kubernetes.io/version: "v2.6.0"
    app.kubernetes.io/part-of: "kiali-operator"
...
