---
# Source: kiali-operator/templates/kialioperator-vpa.yaml
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: &deploymentName kiali-kiali-operator
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: *deploymentName
  updatePolicy:
    updateMode: "Off"
