---
# Source: kiali-operator/charts/kiali-operator/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kiali-operator
  namespace: "kiali-operator"
  labels:
    helm.sh/chart: kiali-operator-2.6.0
    app: kiali-operator
    app.kubernetes.io/name: kiali-operator
    app.kubernetes.io/instance: kiali-operator
    version: "v2.6.0"
    app.kubernetes.io/version: "v2.6.0"
    app.kubernetes.io/part-of: "kiali-operator"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: kiali-operator
      app.kubernetes.io/instance: kiali-operator
  template:
    metadata:
      name: kiali-operator
      namespace: "kiali-operator"
      labels:
        # required for the operator SDK metric service selector
        name: kiali-operator
        helm.sh/chart: kiali-operator-2.6.0
        app: kiali-operator
        app.kubernetes.io/name: kiali-operator
        app.kubernetes.io/instance: kiali-operator
        version: "v2.6.0"
        app.kubernetes.io/version: "v2.6.0"
        app.kubernetes.io/part-of: "kiali-operator"
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "8080"
    spec:
      serviceAccountName: kiali-operator
      containers:
        - name: operator
          image: "quay.io/kiali/kiali-operator:v2.6.0"
          imagePullPolicy: IfNotPresent
          args:
            - "--zap-log-level=info"
            - "--leader-election-id=kiali-operator"
            - "--watches-file=./$(WATCHES_FILE)"
            - "--health-probe-bind-address=:6789"
            - "--metrics-bind-address=:8080"
          terminationMessagePolicy: FallbackToLogsOnError
          readinessProbe:
            httpGet:
              path: /readyz
              port: 6789
            periodSeconds: 30
          livenessProbe:
            httpGet:
              path: /healthz
              port: 6789
            periodSeconds: 30
          startupProbe:
            httpGet:
              path: /healthz
              port: 6789
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 6
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            runAsNonRoot: true
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          volumeMounts:
            - mountPath: /tmp
              name: tmp
          env:
            - name: WATCH_NAMESPACE
              value: kiali-operator
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: ALLOW_AD_HOC_KIALI_NAMESPACE
              value: "true"
            - name: ALLOW_AD_HOC_KIALI_IMAGE
              value: "true"
            - name: ALLOW_AD_HOC_OSSMCONSOLE_IMAGE
              value: "false"
            - name: ALLOW_SECURITY_CONTEXT_OVERRIDE
              value: "false"
            - name: ALLOW_ALL_ACCESSIBLE_NAMESPACES
              value: "true"
            - name: PROFILE_TASKS_TASK_OUTPUT_LIMIT
              value: "100"
            - name: ANSIBLE_DEBUG_LOGS
              value: "false"
            - name: ANSIBLE_VERBOSITY_KIALI_KIALI_IO
              value: "1"
            - name: ANSIBLE_VERBOSITY_OSSMCONSOLE_KIALI_IO
              value: "1"
            - name: ANSIBLE_CONFIG
              value: "/etc/ansible/ansible.cfg"
            - name: ANSIBLE_LOCAL_TEMP
              value: "/tmp/ansible/tmp"
            - name: ANSIBLE_REMOTE_TEMP
              value: "/tmp/ansible/tmp"
            - name: WATCHES_FILE
              value: "watches-os.yaml"
          ports:
            - name: http-metrics
              containerPort: 8080
          resources:
            limits:
              cpu: 0m
              memory: 448Mi
            requests:
              cpu: 0m
              memory: 0Mi
      volumes:
        - name: tmp
          emptyDir: {}
      affinity: {}
