---
# Source: kiali-operator/charts/kiali-operator/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kiali-operator
  namespace: "kiali-operator"
  labels:
    helm.sh/chart: kiali-operator-2.6.0
    app: kiali-operator
    app.kubernetes.io/name: kiali-operator
    app.kubernetes.io/instance: kiali-operator
    version: "v2.6.0"
    app.kubernetes.io/version: "v2.6.0"
    app.kubernetes.io/part-of: "kiali-operator"
